# https://zellwk.com/blog/github-actions-deploy/

name: first-github-action
on: [push]
jobs:
  write-to-console:
    runs-on: ubuntu-latest
    steps:

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts


      - name: Read Known Hosts
        run: cat ~/.ssh/known_hosts


      - name: Adding ssh config
        run: cat ${{ secrets.SSH_PRIVATE_KEY }} >> ~/.ssh/config


      - name: Read ssh config
        run: cat ~/.ssh/config




#      - name: checkout repo
#        uses: actions/checkout@v2.3.4
#
#      - name: show example.text file content
#        run: cat example.text
#
#      - name: Deploy with ansible
#        run: chmod 644 ansible/
#
#      - name: Deploy with ansible step 2
#        run: cd ansible
#
#      - name: Deploy with ansible step 2
#        run: ansible-playbook dev.pipeline.yml -i  hosts -e "ansible_become_password=BsiSrT17!731"



#      - name: Deploy with rsync
#        run: rsync -avz ./ root@${{ secrets.SSH_HOST }}:/home/stephane/deployment/
