name: first-github-action
on: [push]
jobs:
  write-to-console:
    runs-on: ubuntu-latest
    steps:
      - run: pwd

      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - name: show example.text file content
        run: pwd
#        run: cat example.text
#      - name: Deploy with ansible
#        run: chmod 644 infrastructure/deploy
#      - name: Deploy with ansible step 2
#        run: cd infrastructure/deploy
#      - name: Deploy with ansible step 2
#        run: ansible-playbook dev.registry.pipeline.yml -i  hosts


#      - name: Install SSH Key
#        uses: shimataro/ssh-key-action@v2
#        with:
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
#      - name: Adding Known Hosts
#        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
#
#      - name: Deploy with rsync
#        run: rsync -avz ./ root@${{ secrets.SSH_HOST }}:/home/stephane/deployment/
